const mongoose = require('mongoose');

const WardrobeItemSchema = new mongoose.Schema({
    // A reference to the user who owns this item. We will add Firebase UID here later.
    userId: {
        type: String,
        required: true,
    },
    // The primary type of clothing (e.g., "Shirt", "Jeans", "Jacket")
    itemType: {
        type: String,
        required: true,
        trim: true,
    },
    // The primary color of the item
    color: {
        type: String,
        required: true,
        trim: true,
    },
    // URL to the image, which we will store in a cloud service later. For now, it's a placeholder.
    imageUrl: {
        type: String,
        required: true,
    },
    // Tags generated by the AI for future use (e.g., "denim", "formal", "summer")
    tags: [String],
    // Timestamp for when the item was added
    createdAt: {
        type: Date,
        default: Date.now,
    },
});

module.exports = mongoose.model('WardrobeItem', WardrobeItemSchema);
